waiting: |
  <reset>
  <reset><gray>|  <white>Ожидание игроков...
  <reset><gray>| <white>Набрано <gold><players></gold>/<gold><need_players></gold>
  <reset>

waiting-actionbar: "<white>Игроков<gray>: <gold><players></gold>/<gold><need_players></gold>"

countdown: " <gold><time></gold>;<white>До конца ожидания"
timer-stop: |
  
  <red> Таймер остановлен, так как не достигнут минимум игроков!

countdown-actionbar: "<#FF8D21>▶ <#FFDD6C><time></#FFDD6C> <#FF8D21>◀"

not-teaming: "<red> Тим - запрещён!"

start: |
  <reset>
  <reset> <gray>| <#FF551F><bold>К<#FF5C1F><bold>о<#FF6320><bold>р<#FF6A20><bold>о<#FF7120><bold>л<#FF7820><bold>е<#FF7F21><bold>в<#FF8621><bold>с<#FF8D21><bold>к<#FF8621><bold>а<#FF7F21><bold>я <#FF7120><bold>б<#FF6A20><bold>и<#FF6320><bold>т<#FF5C1F><bold>в<#FF551F><bold>а <reset><white>началась!
  <reset> <gray>| <white>Победит сильнейший!
  <reset>

stop: |
  <reset>
  <reset> <gray>|  <#FF551F><bold>К<#FF5C1F><bold>о<#FF6320><bold>р<#FF6A20><bold>о<#FF7120><bold>л<#FF7820><bold>е<#FF7F21><bold>в<#FF8621><bold>с<#FF8D21><bold>к<#FF8621><bold>а<#FF7F21><bold>я <#FF7120><bold>б<#FF6A20><bold>и<#FF6320><bold>т<#FF5C1F><bold>в<#FF551F><bold>а <reset><white>закончилась!
  <reset> <gray>| <white>Увидимся в следующий раз!
  <reset>

sos:
  confirm: "  <white>Внимание, <green>подтвердите <white>запрос, за злоупотребление последует <red>наказание!"
  send: "  Запрос отправлен! Помощь в пути..."

pre-start-teleport: "  <white>Вы телепортированы на арену."

pvp-true: "  <white>PvP <#CFFF1F>включено<white>!"
pvp-false: "  <white>PvP <#FF551F>выключено<white>!"
border-shrink: " <white>Барьер <#FFE71F>сужается<white>, скорее в центр"
death-spectator: "  <white>Вы <#FF1F55>умерли <white>и перешли в режим наблюдателя"

end-close: "  <white>Эндер мир закрыт"
nether-close: "  <white>Незер закрыт"

kit-gived: "  <white>Вы <#C5FF1F>получили <white>свой кит"
only-spectating: "<red> Вы можете только следить за игрой"
kick:
  death: " Вы умерли и выбыли из игры :("
  disqualified: " Вас выгнали из игры"
  is-active: " Игра уже идет, выберите другой режим"
  full-server: "<white> Сервер забит, зайти могут только <yellow><bold> VIP <white>игроки!"

already-stop: "  <white>Игра не запущена!"
stage-notification: "  <white>До следующей стадии <#1F9BFF><time></#1F9BFF>"

sender:
  start: "  <white>Вы запустили быструю игру"
  stop: "  <white>Вы остановили игру"
  kick: "  <white>Вы кикнули <gold><player></gold> из игры"

player-death: "  <white>Один из игроков умер! Осталось <#FFB01F><players></#FFB01F><white>!"

item:
  cannot-use: "  <white>Вы не можете использовать этот предмет"
  head:
    use: "  <white>Вы использовали голову!"
    cooldown: "<gray> Задержка: <yellow><time> <gray>секунд"
  emerald-blade:
    hold: " <red>Вы должны держать Изумрудный Клинок! "
    max-lvl: " <white>Ваш клинок достиг <#C5FF1F>максимального <white>уровня"
    need-amount: " <white>Для улучшения нужно <#C5FF1F>64 изумруда"
    success-upgrade: " <white>Вы <#C5FF1F>улучшили <white>свой клинок!"
    gui: "<green>Улучшение Изумрудного Клинка"
    confirm: "<green>Подтвердить улучшение"
    info:
      - "<white>Текущая острота: <yellow><current_level></yellow>"
      - "<white>Следующий уровень: <yellow><next_level></yellow>"
      - "<white>Стоимость: <green>32 изумруда за 1 уровень"
      - "<white>Максимальный уровень: <red>8"
  dragon-katana:
    blocked: " <white>Нельзя телепортироваться в блоки!"
  midas-sword:
    sharpness-up: " <white>Меч Мидаса усилился!"
  poseidon-trident:
    lightning-blocked: " <white>Нельзя телепортироваться в блоки!"
  ender-bow:
    mode-switched: " <white>Режим переключен"

cooldown:
  started: "  <white>Задержка для <gold><item></gold><gray>: <yellow><time> <white>сек"
  remaining: "  <white>Задержка для <gold><item></gold><gray>: <yellow><time> <white>сек"
  ready: "<gray>[<gold><item></gold><gray>] <white> Перезарядка окончена!"

craft:
  fail: "<red> У вас недостаточно ресурсов для создания этого предмета!"
  available:
    header: "<gold>Доступные крафты:"
    item: "<gray>- <yellow><item> <gray><hover:show_text:'<green>Нажми, чтобы посмотреть крафт'>(клик)</hover>"
  legendary: "  <white>Игрок <#C5FF1F><player> <white>скрафтил <gold><item></gold>"
  limit:
    player: "  <white>Вы исчерпали свой лимит."
    server: "  <white>Этот предмет уже скрафтили."

timer:
  title: "<#FF8D21>▶ <#FFDD6C><time></#FFDD6C> <#FF8D21>◀"
  subtitle: " <white>До начала игры"

block:
  elytra: "  <white>Элитры запрещены"
  shield: "  <white>Щиты запрещены"
  mace: "  <white>Булава запрещена"

stages:
  border-shrink: "Барьер сужается: <time>"
  waiting:
    name: "Ожидание"
  pre-start:
    name: "Подготовка"
  start:
    name: "Начало игры"
  mining:
    name: "Майнинг"
  pre-dm:
    name: "Предезматч"
  deathmatch:
    name: "Дезматч"
  narrowing:
    name: "Сужение"
  nether-open:
    name: "Открытие ада"
  end-open:
    name: "Открытие энда"
  close:
    name: "Финал"
  stop:
    name: "Конец"

deathmatch:
  timer:
    title: "<#FF8D21>▶ <#FFDD6C><time></#FFDD6C> <#FF8D21>◀"
    subtitle: "<white>До исхода битвы "

spec: "  <white>Вы начали слежку за игроком <gold><player></gold>"

check:
  sender: " <white>Вы вызвали на проверку игроку <gold><player></gold>"
  target: |
    <reset>
    <reset>  <#FF5E1F>Вы вызваны на проверку читов
    <reset>
    <reset> <white>вам необходимо отправить модератору
    <reset> <white>свой <dark_aqua><bold> Discord <white>или <red><bold>AnyDesk<white>.
    <reset>
    <reset> <white>Команда - <#FF5E1F>/msg <player> <дискорд/анидеск>
    <reset>

win:
  message: "  <white>Вы выиграли битву!"
  title: "   <#C5FF1F><bold>П<#B6FF28><bold>о<#A7FF31><bold>б<#98FF39><bold>е<#89FF42><bold>д<#7AFF4B><bold>а"
  subtitle: "<white>Вы выиграли!"
  summary: |
    <reset>
    <bold><#FFE36C>И<#FFD95C>Т<#FFCC51>О<#FFBF45>Г<#FFB33A>И <#FFA62E>М<#FF9A23>А<#FF8D17>Т<#FF810C>Ч<#FF7500>А
    <reset>
    <#AFAFAF> Победитель: <#55FF55><winner>
    <reset>
    <#AFAFAF>Лучшие игроки матча:
     <#FFC53D> Легендарный мастер: <#FFFFFF><legend_name> <#AFAFAF>— <#FFC53D><legend_count> <#FFFFFF>легендарок
     <#FF5555> Серийный убийца: <#FFFFFF><killer_name> <#AFAFAF>— <#FF5555><kills> <#FFFFFF>убийств
    <reset>

party:
  already-in-party: "<red> Вы уже в пати."
  created: "<white> Вы создали пати! Пригласить людей - /party invite <игрок>"
  not-in-party: "<red> Вы не в пати."
  only-leader-invite: "<red> Только лидер может приглашать."
  cannot-invite-self: "<red> Вы не можете пригласить себя!"
  max-members: "<red> Вы достигли лимит по приглашенным участникам!"
  target-already-in-party: "<red> Игрок уже в пати."
  player-invited: "<yellow> Игрок <gold><player></gold> приглашён в пати."
  you-were-invited: "<yellow> Вас пригласили в пати игрока <gold><player></gold>. Напишите <green>/party accept</green> или <red>/party decline</red>"
  only-leader-kick: "<red> Только лидер может исключать."
  target-not-in-party: "<red> Игрок не в вашей пати."
  cannot-kick-self: "<red> Вы не можете исключить себя."
  player-kicked: "<green> Игрок <gold><player></gold> исключён из пати."
  player-leave: "<green> Игрок <gold><player></gold> вышел из пати."
  you-were-kicked: "<red> Вы были исключены из пати."
  you-were-leave: "<red> Вы вышли из пати."
  no-invites: "<red> У вас нет приглашений."
  not-exist-anymore: "<red> Команда больше не существует."
  player-joined: "<green> Игрок <gold><player></gold> вступил в команду."
  invite-declined: "<red> Вы отклонили приглашение."
  info: |
    <light_purple> Пати <dark_gray>| <white>Информация о пати:
    <reset> <gray>• <white>Лидер: <gray><leader>
    <reset> <gray>• <white>Участники: <gray><members>
  disband: "<white> Пати была расформирована."
  only-leader-disband: "<red> Только лидер может расформировать команду."
  leader-quit: "<red> Лидер пати вышел из игры. Новым лидером становится <gray><leader>"
  member-quit: "<red> Участник пати <gray><member> вышел из игры"

team:
  already-in-team: "<red> Вы уже в команде."
  no-colors-available: "<red> Не удалось создать команду. Нет доступных цветов."
  created: "<white> Вы создали команду #<gray><id> <gray>(<color><gray>)"
  not-in-team: "<red> Вы не в команде."
  only-leader-invite: "<red> Только лидер может приглашать."
  cannot-invite-self: "<red> Вы не можете пригласить себя!"
  max-members: "<red> Вы достигли лимит по приглашенным участникам!"
  target-already-in-team: "<red> Игрок уже в команде."
  player-invited: "<yellow> Игрок <gold><player></gold> приглашён в команду."
  you-were-invited: "<yellow> Вас пригласили в команду #<gray><id>. Напишите <green>/team accept</green> или <red>/team decline</red>"
  only-leader-kick: "<red> Только лидер может исключать."
  target-not-in-team: "<red> Игрок не в вашей команде."
  cannot-kick-self: "<red> Вы не можете исключить себя."
  player-kicked: "<green> Игрок <gold><player></gold> исключён из команды."
  player-leave: "<green> Игрок <gold><player></gold> вышел из команды."
  you-were-kicked: "<red> Вы были исключены из команды."
  you-were-leave: "<red> Вы вышли из команды."
  no-invites: "<red> У вас нет приглашений."
  not-exist-anymore: "<red> Команда больше не существует."
  player-joined: "<green> Игрок <gold><player></gold> вступил в команду."
  invite-declined: "<red> Вы отклонили приглашение."
  info: |
    <gold> Команда <dark_gray>| <white>Информация о команде #<gray><id> (<color><gray>):
    <reset> <gray>• <white>Лидер: <gray><leader>
    <reset> <gray>• <white>Участники: <gray><members>
  disband: "<white> Команда #<gray><id> была расформирована."
  only-leader-disband: "<red> Только лидер может расформировать команду."
  chat-format: "<player><reset>: <message>"
  leader-death: " <white> Лидер команды <gold><player> <white>умер."
  member-death: " <white> Игрок команды <gold><player> <white>умер."
  leader-quit: " <red> Лидер команды <player> вышел из игры."
  member-quit: " <red> Ваш тиммейт <player> вышел из игры"
  team-death: " <white> Команда <gray>#<id> <white>была полностью уничтожена!"

vote:
  empty: "  <white>Голосование не началось!"
  start: "  <white>Голосование началось - /vote"
  end: "  <white>Голосование закончилось, все команды получили бонусы и выбрали своих лидеров"
  leader: " 👑 <white>По итогам голосования лидером команды становится <gold><player></gold>"

bonus:
  title: ""
  subtitle: "<green> Бонус - <bonus>"

revive:
  too-far-from-center: "<red> Вы слишком далеко от центра!"
  no-team: "<red> У вас нет команды"
  cannot-revive-player: "<red> Этого игрока нельзя воскресить"
  only-teammate: "<red> Воскресить можно только тиммейта"
  not-enough-hearts: "<red> У вас недостаточно сердец для воскрешения (нужно 5)"
  broadcast: "<white> Игрок <green><player></green> <white>был возрожден!"
  success: "<green> Вы успешно воскресили <yellow><target></yellow>"
  target-success: "<green> Вы были воскрешены игроком <yellow><player></yellow>"

play-again: |
  
   <white>В этот раз не повезло :( Хотите сыграть ещё - <hover:show_text:'<green>Сыграть ещё'>[жми сюда]</hover>
